#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "fossflow"
name = "FossFLOW"
description.en = "Isometric diagramming tool"
description.fr = "Outil pour réaliser des diagrammes isométriques"

version = "2026.01.03~ynh1"

maintainers = ["oleole39"]

[upstream]
license = "Unlicense"
userdoc = "https://github.com/stan-smith/FossFLOW?tab=readme-ov-file#how-to-use"
code = "https://github.com/stan-smith/FossFLOW"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "20M"
ram.build = "10M"
ram.runtime = "10M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/fossflow"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.enable_server_storage]
    ask.en = "Offer saving drawings on the server"
    ask.fr = "Permettre de sauvegarder les dessins sur le serveur"
    help.en = "If disabled, nothing leaves the user's browser"
    help.fr = "Si désactivé, rien ne quitte le navigateur de l'utilisateur"
    type = "boolean"
    default = false

[resources]

    [resources.sources]

        [resources.sources.main]
        # This is not used as we are using git clone. It's only here for autoupdate.
        url = "https://github.com/stan-smith/FossFLOW/archive/15f7431d6e14b1ade6003eed5145d9cd8a8cfeda.tar.gz"
        sha256 = "9d3576f9db0a6d5f40413593f8e726d2c40c5ac14b03f900a03d7f8ccddda889"
        prefetch = false
        autoupdate.strategy = "latest_github_commit"
        
        [resources.sources.ynh_build]
        url = "https://github.com/oleole39/fossflow_ynh/releases/download/v2025.12.08-6cb64960/FossFLOW_v2025.12.08-6cb64960_ynh.zip"
        sha256 = "d575133474bf35cded23fd9a32e079be8c2c0147fd189b81490411dcd760be0b"
        format = "zip"
        extract = true
        in_subdir = true

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"
    
    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.data_dir]

	[resources.nodejs]
	version = "22"
