#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "fossflow"
name = "FossFLOW"
description.en = "Isometric diagramming tool"
description.fr = "Outil pour réaliser des diagrammes isométriques"

version = "2026.04.24~ynh1"

maintainers = ["oleole39"]

[upstream]
license = "Unlicense"
userdoc = "https://github.com/stan-smith/FossFLOW?tab=readme-ov-file#how-to-use"
code = "https://github.com/stan-smith/FossFLOW"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "20M"
ram.build = "10M"
ram.runtime = "10M"

[install]
    [install.domain]
    type = "domain"

    #[install.path]
    #type = "path"
    #default = "/fossflow"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.enable_server_storage]
    ask.en = "Offer saving drawings on the server"
    ask.fr = "Permettre de sauvegarder les dessins sur le serveur"
    help.en = "If disabled, nothing leaves the user's browser"
    help.fr = "Si désactivé, rien ne quitte le navigateur de l'utilisateur"
    type = "boolean"
    default = 0
    yes="true"
    no="false"

[resources]

    [resources.sources]

        [resources.sources.main]
        # This is not used as we are using git clone. It's only here for autoupdate.
        url = "https://github.com/stan-smith/FossFLOW/archive/8da9184c03fe80fa6638943b39de291f181e73ac.tar.gz"
        sha256 = "b1c53d45fdf5518792161ae13247345606fa7ae17bc382a439c2132a2c1e71d7"
        prefetch = false
        autoupdate.strategy = "latest_github_commit"
        
        [resources.sources.ynh_build]
        url = "https://github.com/oleole39/fossflow_ynh/releases/download/v2026.04.24-8da9184c/FossFLOW_v2026.04.24-8da9184c_ynh.zip"
        sha256 = "57cca1e727c735511b4273dd0042c04765326d20ba87bf1184e8f9dd5213312c"
        format = "zip"
        extract = true
        in_subdir = true

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"
    
    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.data_dir]

	[resources.nodejs]
	version = "22"
