#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "fossflow"
name = "FossFLOW"
description.en = "Isometric diagramming tool"
description.fr = "Outil pour réaliser des diagrammes isométriques"

version = "2026.04.19~ynh1"

maintainers = ["oleole39"]

[upstream]
license = "Unlicense"
userdoc = "https://github.com/stan-smith/FossFLOW?tab=readme-ov-file#how-to-use"
code = "https://github.com/stan-smith/FossFLOW"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "20M"
ram.build = "10M"
ram.runtime = "10M"

[install]
    [install.domain]
    type = "domain"

    #[install.path]
    #type = "path"
    #default = "/fossflow"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.enable_server_storage]
    ask.en = "Offer saving drawings on the server"
    ask.fr = "Permettre de sauvegarder les dessins sur le serveur"
    help.en = "If disabled, nothing leaves the user's browser"
    help.fr = "Si désactivé, rien ne quitte le navigateur de l'utilisateur"
    type = "boolean"
    default = 0
    yes="true"
    no="false"

[resources]

    [resources.sources]

        [resources.sources.main]
        # This is not used as we are using git clone. It's only here for autoupdate.
        url = "https://github.com/stan-smith/FossFLOW/archive/f11fd8154da0bbcc8c6ef0c535bee2344a053105.tar.gz"
        sha256 = "a21a67311c6ee08f29ddf7db06974305cfc843ec65fe331277b6c046c189ac00"
        prefetch = false
        autoupdate.strategy = "latest_github_commit"
        
        [resources.sources.ynh_build]
        url = "https://github.com/oleole39/fossflow_ynh/releases/download/v2026.04.12-051c10df/FossFLOW_v2026.04.12-051c10df_ynh.zip"
        sha256 = "52894bdf2d1f6a830ed9fc1144fe9a4d8af9e76cf5dbe8f337574f2e96f60f3a"
        format = "zip"
        extract = true
        in_subdir = true

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"
    
    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.data_dir]

	[resources.nodejs]
	version = "22"
