#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir" --source_id="ynh_build"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# INSTALL BACKEND
#=================================================
ynh_script_progression "Installing $app backend..."

# Deploy optional backend
pushd "$install_dir/backend/"
	ynh_hide_warnings npm install --production
popd
ynh_config_add --template="systemd.service" --destination="/etc/systemd/system/$app.service"

# Enable optional backend according to admin choice
if [ "$enable_server_storage" == "true" ]; then
	systemctl enable "$app.service" --quiet
	systemctl daemon-reload
	yunohost service add "$app" --description="FossFLOW persisent storage backend" --log="/var/log/$app/$app.log"
	ynh_systemctl --service="$app" --action="start" --log_path="systemd"
fi

# Allow frontend access to saved diagrams 
chown -R "$app:www-data" "$data_dir"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Installation of $app completed"
