#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

if [[ "$path" != "/" ]]; then
    ynh_die "Installing Fossflow on a subpath is not supported anymore since v2025.12.08~ynh1 (cf. https://github.com/YunoHost-Apps/fossflow_ynh/pull/37)"
fi

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --source_id="ynh_build" --full_replace

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

ynh_config_add --template=".env" --destination="$install_dir/.env"

# Deploy optional backend
pushd "$install_dir/backend/"
	ynh_hide_warnings npm install --production
popd
ynh_config_add --template="systemd.service" --destination="/etc/systemd/system/$app.service"

# Enable optional backend according to admin choice
if [ "$enable_server_storage" -eq 1 ]; then
	systemctl enable "$app.service" --quiet
	systemctl daemon-reload
	yunohost service add "$app" --description="FossFLOW persisent storage backend" --log="/var/log/$app/$app.log"
	ynh_systemctl --service="$app" --action="start" --log_path="systemd"
fi

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Upgrade of $app completed"
